# Generated by Django 4.2.3 on 2023-07-28 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0002_tarea_ultima_modificacion_por'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarea',
            name='ultima_modificacion_por',
        ),
    ]
